// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT7P5By2bpeCzCLHRwzyITjQRMeK8Wb_Q',
    appId: '1:253079586640:web:a14beaca22e87cb9114e55',
    messagingSenderId: '253079586640',
    projectId: 'project-gsc-c136c',
    authDomain: 'project-gsc-c136c.firebaseapp.com',
    storageBucket: 'project-gsc-c136c.appspot.com',
    measurementId: 'G-4JNFN50BDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMT4F8uA3tOpvTCQTNX5TV-NAxgTMvuI',
    appId: '1:253079586640:android:f63647e3612bb5e0114e55',
    messagingSenderId: '253079586640',
    projectId: 'project-gsc-c136c',
    storageBucket: 'project-gsc-c136c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV3z_PjxvAQTPDUjzsrarbB3LGluVUK7Q',
    appId: '1:253079586640:ios:2da8140a1d68d3ba114e55',
    messagingSenderId: '253079586640',
    projectId: 'project-gsc-c136c',
    storageBucket: 'project-gsc-c136c.appspot.com',
    iosBundleId: 'com.example.projectGsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV3z_PjxvAQTPDUjzsrarbB3LGluVUK7Q',
    appId: '1:253079586640:ios:ee47e1ce72175770114e55',
    messagingSenderId: '253079586640',
    projectId: 'project-gsc-c136c',
    storageBucket: 'project-gsc-c136c.appspot.com',
    iosBundleId: 'com.example.projectGsc.RunnerTests',
  );
}
